### ISSUE TITLE
Building in armv7l VM produces "unsupported arch" from electron-builder

### ISSUE THREAD

**Issue by MatthewCroughan** [UnchartedBull/OctoDash#760]
I'm trying to produce some CI so that this application can be deployed to raspberry pi's. In doing this I am using a docker build daemon running on a remote system that is `armv7l` architecture. 

When running the following commands after git cloning the repository, I cannot get through the full process, as it errors out at some point.

`cd OctoDash && npm install && npm run pack deb`

`uname -m` on the machine returns armv7l.

```
[octodash]   Compiling @angular/material/tree : es2015 as esm2015
[octodash]   
[Info]       Still Working...
[octodash]   Generating ES5 bundles for differential loading...
[octodash]   ES5 bundle generation complete.
[octodash]   chunk {0} runtime-esnext.1eba213af0b233498d9d.js (runtime) 1.45 kB [entry] [rendered]
[octodash]   chunk {0} runtime-es5.1eba213af0b233498d9d.js (runtime) 1.45 kB [entry] [rendered]
[octodash]   chunk {2} polyfills-esnext.f2c5ab749249a66bdf26.js (polyfills) 36.1 kB [initial] [rendered]
[octodash]   chunk {2} polyfills-es5.f2c5ab749249a66bdf26.js (polyfills) 39.6 kB [initial] [rendered]
[octodash]   chunk {3} polyfills-es5.049f620af8c864cf4d88.js (polyfills-es5) 129 kB [initial] [rendered]
[octodash]   chunk {1} main-esnext.8e55e6b18c48170f768d.js (main) 1.75 MB [initial] [rendered]
[octodash]   chunk {1} main-es5.8e55e6b18c48170f768d.js (main) 1.85 MB [initial] [rendered]
[octodash]   chunk {4} styles.db64e758ba1ce0345408.css (styles) 64.1 kB [initial] [rendered]
[octodash]   Date: 2020-06-24T13:19:29.991Z - Hash: ad4d51671cc61a8fdf40 - Time: 179329ms
[octodash]   
[octodash]   
[octodash]     ⨯ 
[octodash]   Unsupported arch arm  stackTrace=
[octodash]                               Error: Unsupported arch arm
[octodash]                                   at archFromString (/usr/src/app/OctoDash/node_modules/builder-util/src/arch.ts:43:13)
[octodash]                                   at commonArch (/usr/src/app/OctoDash/node_modules/electron-builder/src/builder.ts:54:62)
[octodash]                                   at processTargets (/usr/src/app/OctoDash/node_modules/electron-builder/src/builder.ts:77:28)
[octodash]                                   at normalizeOptions (/usr/src/app/OctoDash/node_modules/electron-builder/src/builder.ts:89:5)
[octodash]                                   at build (/usr/src/app/OctoDash/node_modules/electron-builder/src/builder.ts:217:24)
[octodash]                                   at /usr/src/app/OctoDash/node_modules/electron-builder/src/cli/cli.ts:46:19
```

**Comment by UnchartedBull** [comment]
Why would you want to build an armv7l though? Cross-compiling works just fine with electron. Anyways here is the issue on the electron-builder repository: https://github.com/electron-userland/electron-builder/issues/4279. The trick probably is adding `-armv7l` to the `npm run:pack` script. If that doesn't work please open an issue in the electron-builder repository :)
